### ISSUE TITLE
Fork "Rune: Commerce"

### ISSUE THREAD

**Issue by ergonlogic** [poetic/rune#86]
The recent addition of Commerce adds more that 30 modules. This bloats rune's contrib modules by more that 20% (so far). I think keeping a slimmer base distribution is a better way to go, since relatively few projects require Commerce. A fork would be easy to maintain, since it'd really just require renaming a few files in the project root.

**Comment by RealLukeMartin** [comment]
Our main goal going into this was to have one unified Rune profile, due to new commerce sites coming along and past headaches with sites that started non-commerce and way down the road turned out needing some commerce functionality. Having the commerce modules already in the profile adds convenience, but see now it does add a ton of extra overhead and maintenance.

With a fork, would it be possible to have it just plug-in to the base rune profile when we need it on a new platform to be built, or is a completely separate "rune-commerce" profile the only feasible way to do this?
